// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKWYrte5VwMgrN_1VKp8VAIlmD7yQ_FVw',
    appId: '1:56116314664:web:2c1bb07c641b9ae754ab1d',
    messagingSenderId: '56116314664',
    projectId: 'uhsplus',
    authDomain: 'uhsplus.firebaseapp.com',
    storageBucket: 'uhsplus.appspot.com',
    measurementId: 'G-977KLS33FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6rAYNeCd-UftZpZX_AkScuEbf5gDpmTg',
    appId: '1:56116314664:android:9af9f3efe17a8d4254ab1d',
    messagingSenderId: '56116314664',
    projectId: 'uhsplus',
    storageBucket: 'uhsplus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgOa6L4ufjPfA3788IWfoXqPNbElAOEcU',
    appId: '1:56116314664:ios:f041f50eeff1216a54ab1d',
    messagingSenderId: '56116314664',
    projectId: 'uhsplus',
    storageBucket: 'uhsplus.appspot.com',
    iosBundleId: 'com.example.wolfpackapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgOa6L4ufjPfA3788IWfoXqPNbElAOEcU',
    appId: '1:56116314664:ios:f041f50eeff1216a54ab1d',
    messagingSenderId: '56116314664',
    projectId: 'uhsplus',
    storageBucket: 'uhsplus.appspot.com',
    iosBundleId: 'com.example.wolfpackapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKWYrte5VwMgrN_1VKp8VAIlmD7yQ_FVw',
    appId: '1:56116314664:web:5bc232a2e430cdf254ab1d',
    messagingSenderId: '56116314664',
    projectId: 'uhsplus',
    authDomain: 'uhsplus.firebaseapp.com',
    storageBucket: 'uhsplus.appspot.com',
    measurementId: 'G-LNL6WPEJET',
  );

}